### ISSUE TITLE
实际修改的部分有完档描述吗

### ISSUE THREAD

**Issue by Johnnyzhoutq** [tanjiancheng/alibaba-sentinel-dashboard-nacos#1]
实际修改的部分有完档描述吗，工程代码比较多

**Comment by Qoooooooooooo** [comment]
同问^^

**Comment by tanjiancheng** [comment]
具体修改的东西我在代码里打了标记，可以查找项目代码找到
`add by tam`
表示新增的文件或者代码
`modify by tam`
表示修改的文件或者代码
详细可以查看这里的commit [(7b634bd)](https://github.com/tanjiancheng/alibaba-sentinel-dashboard-nacos/commit/c2e94ab22451f6c26b6e52038137782f63bc297f)
