### ISSUE TITLE
能否把族点链路和单机页面里的V1升级成V2

### ISSUE THREAD

**Issue by Qoooooooooooo** [tanjiancheng/alibaba-sentinel-dashboard-nacos#2]
那两个地方依旧是v1接口 内存储存

**Comment by tanjiancheng** [comment]
> 那两个地方依旧是v1接口 内存储存

![image](https://user-images.githubusercontent.com/7401570/71657981-108c1800-2d7d-11ea-9bca-38df81dc96cc.png)

流控规则->回到单机页面的的是官方例子默认保留的，这个里面还是走内存储存，你只要不切换过去，默认的流控规则是存储到nacos的，官方的意图是你可以保留这块内存跟nacos持久化并存，内存的会优先覆盖nacos的配置，不过我觉得竟然用nacos存储的话这块其实可以去掉的，如果需要每个功能都可以切换到这个单机页面，可以参考这块自行实现，去掉这个按钮方式到
```
\src\main\webapp\resources\app\views\flow_v2.html
```
找到
```
<a class="btn btn-default-inverse" style="float: right; margin-right: 10px;" ui-sref="dashboard.flowV1({app: app})">
      回到单机页面
</a>
```
注释就行了，目前我已注释并提交了 [修改族点链路流控为v2和去掉单机页面](https://github.com/tanjiancheng/alibaba-sentinel-dashboard-nacos/commit/7b634bdf7bacaa4584b4ba5124f72ccda83db8b9)

**Comment by Qoooooooooooo** [comment]
感谢作者，为我节省时间^^
