### ISSUE TITLE
dashboard集成后，启动网关，发现nacos上会出现两个配置文件，一个不带-dashboard，一个带-dashboard，两个文件内容还不太一样

### ISSUE THREAD

**Issue by witchang** [tanjiancheng/alibaba-sentinel-dashboard-nacos#3]

**Comment by tanjiancheng** [comment]
带-dashboard是给sentine控制后台显示规则使用，不带-dashboard的是给对应的gateway控流规则使用的，就是gateway对应的控流规则会拉取不带-dashboard的然后加载进去，后台启动会拉取带-dashboard的规则同步到后台显示，他们相同字段配置值是一致的，分开2个是因为有些配置是后台特须需要，所以分开2个保存
