### ISSUE TITLE
持久化是持久化了，好像限流配置了没有效果

### ISSUE THREAD

**Issue by shxdos** [tanjiancheng/alibaba-sentinel-dashboard-nacos#7]

**Comment by tanjiancheng** [comment]
可以附上截图我看看你是怎么配置的吗？

**Comment by tanjiancheng** [comment]
![image](https://user-images.githubusercontent.com/7401570/91372891-7c108180-e847-11ea-9090-2e8fe51e0691.png)

我设置了一秒一个通过，多刷几次接口就会返回如下的信息了，应该是没问题的

![image](https://user-images.githubusercontent.com/7401570/91372915-8a5e9d80-e847-11ea-9914-59cc1ab3369b.png)

**Comment by shxdos** [comment]
> 可以附上截图我看看你是怎么配置的吗？

![image](https://user-images.githubusercontent.com/7435679/91377280-a0715b80-e851-11ea-8f40-089c5e64f1f8.png)

**Comment by shxdos** [comment]
方便加个QQ指导一下吗853281746
